const fs = require('fs-extra')
fs.mkdirSync('./folder1')
fs.createFileSync('./folder1/nfile.txt')
fs.writeFileSync('./folder1/nfile.txt', 'lyric')
fs.mkdirSync('./folder2')
fs.moveSync('./folder1/nfile.txt', './folder2/nfile.txt')
fs.removeSync('./folder2/nfile.txt')
fs.removeSync('./folder1')
fs.removeSync('./folder2')
console.log('hello')